# Generated by Django 5.0.9 on 2024-10-25 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('requirements', models.TextField()),
                ('min_educational_level', models.CharField(choices=[('elementary', 'Ensino Fundamental'), ('high_school', 'Ensino médio'), ('technologist', 'Tecnólogo'), ('bachelors', 'Ensino Superior'), ('postgraduate', 'Pós / MBA / Mestrado'), ('doctorate', 'Doutorado')], max_length=64)),
                ('salary_range', models.CharField(choices=[('up_to_1000', 'Up to 1000'), ('from_1001_to_2000', 'From 1001 to 2000'), ('from_2001_to_3000', 'From 2001 to 3000'), ('above_3000', 'Above 3000')], max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField()),
                ('educational_level', models.CharField(choices=[('elementary', 'Ensino Fundamental'), ('high_school', 'Ensino médio'), ('technologist', 'Tecnólogo'), ('bachelors', 'Ensino Superior'), ('postgraduate', 'Pós / MBA / Mestrado'), ('doctorate', 'Doutorado')], max_length=64)),
                ('salary_range_expectation', models.CharField(choices=[('up_to_1000', 'Up to 1000'), ('from_1001_to_2000', 'From 1001 to 2000'), ('from_2001_to_3000', 'From 2001 to 3000'), ('above_3000', 'Above 3000')], max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobListingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_ranking', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.joblisting')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
